[package]
name = "aoe2js"
description = "CLI utility to convert an AoE2 recorded game to JSON"
license = "MIT"
version = "0.1.18"
edition = "2021"

[dependencies]
aoe2rec = { version = "0.6.0", path = "../aoe2rec" }
clap = { version = "4.5.20", features = ["derive"] }
serde_json = "1.0.132"
